theme: minima

title: Mark's programming notes
description: >-
  Mainly just a bunch of links to help me remember what I'm working on from day to day.
  Stuff about programming. .NET, SQL Server, JavaScript and whatever else.

github_username: balb
# show_excerpts: true
plugins:
  - jekyll-feed # for feed.xml
